[project]
name = "adding-datasets-to-kg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "robokop-orion>=0.1.3",
    "pandas",
    "numpy"
]

[build-system]
requires = ["uv_build >= 0.8.0"]
build-backend = "uv_build"

